### ISSUE TITLE
[question]  consensus protocol for `ios`

### ISSUE THREAD

**Issue by andy2046** [heidi-ann/ios#30]
[question]

@heidi-ann 

is `ios` the implementation of [A Generalised Solution to Distributed Consensus](https://arxiv.org/abs/1902.06776)?

which consensus protocol it is using?

**Comment by heidihoward** [comment]
No, Ios predates this work. It's built on a custom consensus algorithm which I did not get around to publishing.

**Comment by andy2046** [comment]
@heidi-ann thanks for the confirmation, is there any implementation based on [A Generalised Solution to Distributed Consensus](https://arxiv.org/abs/1902.06776)?

**Comment by heidihoward** [comment]
Not that I know of

**Comment by andy2046** [comment]
thanks
